version: '3'
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./Online_Retail_Sample_100k.csv:/Online_Retail_Sample_100k.csv
    environment:
      - CLUSTER_NAME=test
      - HDFS_CONF_dfs_blocksize=67108864
    env_file:
      - ./hadoop.env
    deploy:
      resources:
        limits:
          memory: 512M

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    deploy:
      resources:
        limits:
          memory: 512M

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    restart: always
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    deploy:
      resources:
        limits:
          memory: 512M

  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    restart: always
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    deploy:
      resources:
        limits:
          memory: 512M

  spark:
    image: bitnami/spark:latest
    container_name: spark
    depends_on:
      - namenode
    volumes:
      - ./Online_Retail_Sample_100k.csv:/Online_Retail_Sample_100k.csv
      - ./spark_app.py:/app/spark_app.py
    environment:
      - SPARK_MASTER=spark://spark:7077
    entrypoint: ["/bin/bash", "-c", "while :; do sleep 1000; done"]

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3: